# Site settings
title: A Breadth-First Life
email: warren.j.francis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Interesting stuff I'm learning and doing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://geekoftheweek.github.io" # the base hostname & protocol for your site
twitter_username: maybe_warren
github_username:  geekoftheweek

# Build settings
markdown: kramdown
